development:
  :asx_list_url: 'http://www.asx.com.au/asx/research/ASXListedCompanies.csv'
  :filter_volume: 50000
  :filter_price: 0.2
  :max_days: 800
  :exchange_name: 'ASX'
  :site_url: 'http://localhost:3000'
  :images_dir: 'app/assets/images'
  :mma_months: 12
